// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PollVoteBackend.Data;

namespace PollVoteBackend.Migrations
{
    [DbContext(typeof(PollsContext))]
    [Migration("20200818075925_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PollVoteBackend.Models.Poll", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<List<string>>("Choices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<int>>("ChoicesAnswers")
                        .HasColumnType("integer[]");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("text");

                    b.Property<string>("DeleteToken")
                        .HasColumnType("text");

                    b.Property<string>("EndedOn")
                        .HasColumnType("text");

                    b.Property<int>("ExpiresOnChoices")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Poll");
                });
#pragma warning restore 612, 618
        }
    }
}
